apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: app-v2
      app.kubernetes.io/component: app-v2
      app.kubernetes.io/instance: app-v2
    name: app-v2
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: app-v2
      app.kubernetes.io/component: app-v2
      app.kubernetes.io/instance: app-v2
    name: app-v2
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: app-v2:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: v3
        uri: https://github.com/ggianini/OpenShift-Demo-Client
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.4-ubi8
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: vIbBAnmK5jpn8o19erMt
      type: GitHub
    - generic:
        secret: 74RKg6puWNmB-hxbjtye
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"app-v2:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app-v2\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: app-v2
      app.kubernetes.io/component: app-v2
      app.kubernetes.io/instance: app-v2
    name: app-v2
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: app-v2
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: app-v2
      spec:
        containers:
        - env:
          # - name: DEMO_SUBTITLE
          #   value: Subtitulo
          # - name: DEMO_TITLE
          #   value: Demo Red Hat!
          - name: DEMO_SUBTITLE 
            valueFrom:
              configMapKeyRef:
                name: app-v2-configmap 
                key: DEMO_SUBTITLE 
          - name: DEMO_TITLE 
            valueFrom:
              configMapKeyRef:
                name: app-v2-configmap 
                key: DEMO_TITLE 
          image: ' '
          name: app-v2
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: app-v2
      app.kubernetes.io/component: app-v2
      app.kubernetes.io/instance: app-v2
    name: app-v2
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: app-v2
  status:
    loadBalancer: {}
kind: List
metadata: {}
